-- V2 - Donnees de demonstration
-- Migration distincte du schema (ENF6, decision Z4) : le correcteur ne demarre
-- jamais sur une application vide. Une promotion, des etudiants, une session
-- ouverte avec son code, des presences, un exercice et une relecture en attente.
-- Les identifiants sont poses explicitement ; les insertions suivantes reprennent
-- la sequence au-dela (GENERATED BY DEFAULT AS IDENTITY).

INSERT INTO promotion (id, nom) VALUES (1, 'KFOKAM48 - Promotion 2026');

INSERT INTO etudiant (id, nom, promotion_id) VALUES
    (1, 'Amina Ngo Bassong', 1),
    (2, 'Bertrand Etoundi', 1),
    (3, 'Chantal Fouda', 1),
    (4, 'Desire Kamdem', 1),
    (5, 'Estelle Mbarga', 1),
    (6, 'Fabrice Onana', 1),
    (7, 'Gisele Tchoumi', 1);

-- Session ouverte au demarrage : le code reste utilisable 15 minutes (RG1).
INSERT INTO session_cours (id, titre, promotion_id, code, ouverture_at, expiration_at, cloturee_at)
VALUES (1, 'Introduction au genie logiciel', 1, 'KD2M4A',
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '15' MINUTE, NULL);

-- Trois etudiants presents (source ETUDIANT, RG3 respectee : un par session).
INSERT INTO presence (id, session_id, etudiant_id, source, marquee_at) VALUES
    (1, 1, 1, 'ETUDIANT', CURRENT_TIMESTAMP),
    (2, 1, 2, 'ETUDIANT', CURRENT_TIMESTAMP),
    (3, 1, 3, 'ETUDIANT', CURRENT_TIMESTAMP);

-- Un exercice depose par Amina, affecte a Bertrand (present, autre que l'auteur,
-- RG11/RG12), encore a rendre : le relecteur a quelque chose a faire des l'arrivee.
INSERT INTO exercice (id, session_id, etudiant_id, lien, statut, depose_at, modifie_at)
VALUES (1, 1, 1, 'https://github.com/amina-ngb/exercice-1', 'EN_ATTENTE_RELECTURE', CURRENT_TIMESTAMP, NULL);

INSERT INTO relecture (id, exercice_id, relecteur_id, affectee_at, rendue_at)
VALUES (1, 1, 2, CURRENT_TIMESTAMP, NULL);

-- Les identifiants ci-dessus etant explicites, les sequences d'identite
-- repartent au-dela : sans cela, la prochaine session creee par l'API
-- regenererait l'identifiant 1 deja pris (erreur 23505).
ALTER TABLE promotion ALTER COLUMN id RESTART WITH 2;
ALTER TABLE etudiant ALTER COLUMN id RESTART WITH 8;
ALTER TABLE session_cours ALTER COLUMN id RESTART WITH 2;
ALTER TABLE presence ALTER COLUMN id RESTART WITH 4;
ALTER TABLE exercice ALTER COLUMN id RESTART WITH 2;
ALTER TABLE relecture ALTER COLUMN id RESTART WITH 2;
